development:
  adapter: postgresql
  encoding: unicode
  database: event_tracker_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: event_tracker_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: event_tracker_production
  pool: 5
  username: event_tracker
  password:
